Backport Erlang time64 patch
This is currently causing build failures on 32bit architectures for 4.0 (where we updated to Ubuntu 24.04):

    /usr/include/features-time64.h:26:5: error: #error "_TIME_BITS=64 is allowed only with _FILE_OFFSET_BITS=64"

This is the same patch applied by Debian and Ubuntu to fix the same problem (and applied there in both Erlang 25 and 26, as we have here, so I've applied it across both for simplicity/consistency).