Fix 3.13 build failure on arm32v7 by moving to Ubuntu 24.04
+ apt-get install --yes --no-install-recommends ca-certificates gosu tzdata
...
+ gosu nobody true
panic: unaligned 64-bit atomic operation
preempt off reason: doAllThreadsSyscall
fatal error: panic during preemptoff